### ISSUE TITLE
Can't download via Homebrew

### ISSUE THREAD

**Issue by kolyan94** [lwouis/fat-drive-sorter#3]
When I tried to run `brew install --cask fat-drive-sorter` I got an error:
Error: No casks found for fat-drive-sorter.

Also, I can't find `fat-drive-sorter` in the homebrew web site.

**Comment by lwouis** [comment]
Hi,

Yes, sorry about that. When I created this projet, I reused my work from https://github.com/lwouis/alt-tab-macos. I thought that I would add a homebrew cask easily. When I submitted the PR to the homebrew team, they refused it because the project wasn't popular yet.

I'll only be able to add this projet to homebrew when the project reaches more popularity. For now, you can only [download the app from the website](https://github.com/lwouis/fat-drive-sorter/releases), or built it from source.

Thank you 🙇
